name: Build and Test

on:
  push:
    branches:
      - main # Change this to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: 8

      - name: Run Checkstyle Main
        run: ./gradlew checkstyleMain

      - name: Run Checkstyle Test
        run: ./gradlew checkstyleTest

      - name: Build
        run: ./gradlew build -x test -x checkstyleMain -x checkStyleTest

      - name: Test
        run: ./gradlew test

      - name: Generate JaCoCo Report
        run: ./gradlew jacocoTestReport

      # Store the generated code coverage report as an artifact
      - name: Store JaCoCo Report
        uses: actions/upload-artifact@v2
        with:
          name: jacoco-report
          path: build/reports/jacoco/test/html