ALTER TABLE days ALTER COLUMN id RESTART WITH 1;
ALTER TABLE artists ALTER COLUMN id RESTART WITH 1;
ALTER TABLE organizers ALTER COLUMN id RESTART WITH 1;

DELETE FROM organizers;
DELETE FROM days;
DELETE FROM artists;


